Repository ansible-collections/servicenow.itsm, pull requests merged in 2022-08, with the labels that each got.

#188 Control sysparm_display_value behavior in *_info modules
  changelogs/fragments/188_control_sysparm_display_value_in_info_modules.yml
  plugins/doc_fragments/sysparm_display_value.py
  plugins/module_utils/arguments.py
  plugins/module_utils/utils.py
  plugins/modules/change_request_info.py
  plugins/modules/change_request_task_info.py
  plugins/modules/configuration_item_info.py
  plugins/modules/incident_info.py
  plugins/modules/problem_info.py
  plugins/modules/problem_task_info.py
  tests/unit/plugins/modules/test_change_request_info.py
  tests/unit/plugins/modules/test_change_request_task_info.py
  tests/unit/plugins/modules/test_configuration_item_info.py
  tests/unit/plugins/modules/test_incident_info.py
  tests/unit/plugins/modules/test_problem_info.py
  tests/unit/plugins/modules/test_problem_task_info.py
Labels: type/enhancement, mergeit

#197 force click==8.0.4 to fix sanity check error, fix #196
  sanity.requirements
Labels: type/bug, mergeit

#193 Adapt integration tests for attachment module due to changes on PR 192 (configuration item idempotency)
  changelogs/fragments/adapt_attachment_integration_tests.yml
  tests/integration/targets/attachment/tasks/main.yml
Labels: mergeit

#200 Revert "Stopgap api functionality (#179)"
  .flake8
  changelogs/fragments/179_encode_servicenow_rest_api_module_in_ansible.yml
  plugins/module_utils/api.py
  plugins/module_utils/utils.py
  plugins/modules/api.py
  plugins/modules/api_info.py
  tests/integration/targets/api/tasks/main.yml
  tests/unit/plugins/modules/test_api.py
  tests/unit/plugins/modules/test_api_info.py
Labels: mergeit

#194 Fix attachment integration tests bugs - missing register variable
  changelogs/fragments/attachment_integration_tests_missing_register_variables.yml
  tests/integration/targets/attachment/tasks/main.yml
Labels: mergeit

#198 Raw API module: Basic
  changelogs/fragments/179_encode_servicenow_rest_api_module_in_ansible.yml
  plugins/module_utils/api.py
  plugins/module_utils/utils.py
  plugins/modules/api.py
  plugins/modules/api_info.py
  tests/integration/targets/api/tasks/main.yml
  tests/unit/plugins/modules/test_api.py
  tests/unit/plugins/modules/test_api_info.py
Labels: type/enhancement, mergeit

#185 Features/configuration item batch result
  changelogs/fragments/configuration_batch_item_return_value.yml
  plugins/modules/configuration_item_batch.py
  tests/unit/plugins/modules/test_configuration_item_batch.py
Labels: type/enhancement, mergeit

#190 Enhance `servicenow.itsm.now` and `servicenow.itsm.*_info` modules by adding alternative way to filter out the results
  changelogs/fragments/190_add_alternative_way_to_filter_results.yml
  plugins/doc_fragments/query.py
  plugins/inventory/now.py
  plugins/module_utils/arguments.py
  plugins/modules/change_request_info.py
  plugins/modules/change_request_task_info.py
  plugins/modules/configuration_item_info.py
  plugins/modules/incident_info.py
  plugins/modules/problem_info.py
  plugins/modules/problem_task_info.py
  tests/unit/plugins/modules/test_change_request_info.py
  tests/unit/plugins/modules/test_change_request_task_info.py
  tests/unit/plugins/modules/test_configuration_item_info.py
  tests/unit/plugins/modules/test_incident_info.py
  tests/unit/plugins/modules/test_problem_info.py
  tests/unit/plugins/modules/test_problem_task_info.py
Labels: type/enhancement, mergeit

#201 Raw API module: Follow-up (built-in template processing capabilities)
  changelogs/fragments/180_enhance_api_module_by_adding_field_template.yml
  plugins/action/api.py
  plugins/module_utils/api.py
  plugins/modules/api.py
  plugins/modules/api_info.py
  tests/integration/targets/api/tasks/main.yml
  tests/integration/targets/api/templates/test_template_patch.j2
  tests/integration/targets/api/templates/test_template_post.j2
  tests/unit/plugins/action/test_api.py
  tests/unit/plugins/modules/test_api.py
Labels: type/enhancement, mergeit

#192 Configuration_item module: implement idempotence (issue #71)
  changelogs/fragments/71_configuration_item_implement_idempotence.yml
  plugins/modules/configuration_item.py
  plugins/modules/configuration_item_info.py
  tests/integration/targets/configuration_item/tasks/main.yml
  tests/unit/plugins/modules/test_configuration_item.py
  tests/unit/plugins/modules/test_configuration_item_info.py
Labels: type/enhancement, mergeit

#204 Fix sanity error in test_api
  changelogs/fragments/test_api_remove_unused_import.yml
  tests/unit/plugins/modules/test_api.py
Labels: mergeit

#202 [bp/1.4]: Added user maping doc
  docs/user_mapping.md
Labels: type/documentation

#205 Fix attachment unit tests
  changelogs/fragments/test-attachment.yaml
  tests/unit/plugins/modules/test_attachment.py
Labels: type/enhancement, mergeit
