Repository ansible-collections/servicenow.itsm, pull requests merged in 2022-07, with the labels that each got.

#177 Bugfix/resolve sanity tests errors
  .flake8
  sanity.requirements
Labels: mergeit

#186 attachment: A module to download attachment using sys_id
  changelogs/fragments/attachments.yaml
  plugins/module_utils/attachment.py
  plugins/modules/attachment.py
  tests/integration/targets/attachment/tasks/main.yml
  tests/unit/plugins/module_utils/test_attachment.py
  tests/unit/plugins/modules/test_attachment_module.py
Labels: type/enhancement, mergeit

#184 Fix default exclude_reference_link in `table.py`
  changelogs/fragments/184_fix_default_exclude_reference_link.yml
  plugins/module_utils/table.py
Labels: mergeit

#179 Stopgap api functionality
  .flake8
  changelogs/fragments/179_encode_servicenow_rest_api_module_in_ansible.yml
  plugins/module_utils/api.py
  plugins/module_utils/utils.py
  plugins/modules/api.py
  plugins/modules/api_info.py
  tests/integration/targets/api/tasks/main.yml
  tests/unit/plugins/modules/test_api.py
  tests/unit/plugins/modules/test_api_info.py
Labels: mergeit, type/story
