Repository ansible-collections/servicenow.itsm, pull requests merged in 2024-02, with the labels that each got.

#294 Add missing env to docs for sysparm_query
  changelogs/fragments/now_env_sysparm_query.yml
  plugins/inventory/now.py
Labels: type/bug

#208 add return_fields parmeter to the configuration_item_info module
  changelogs/fragments/configuration_item_info_return_fields.yml
  plugins/modules/configuration_item_info.py
Labels: type/enhancement

#298 Fix change_request and change_request_task int tests
  tests/integration/targets/change_request/tasks/main.yml
  tests/integration/targets/change_request_task/tasks/main.yml
Labels: type/tests

#302 Add integration tests for #208
  tests/integration/targets/configuration_item/tasks/main.yml
Labels: type/tests

#301 Allow using assignment_group sys_id in queries
  changelogs/fragments/change_request.yml
  changelogs/fragments/change_request_task_assignment_group.yml
  plugins/module_utils/table.py
  plugins/modules/change_request.py
  plugins/modules/change_request_task.py
  tests/integration/targets/change_request/tasks/main.yml
  tests/integration/targets/change_request_task/tasks/main.yml
  tests/unit/plugins/modules/test_change_request.py
  tests/unit/plugins/modules/test_change_request_task.py
Labels: type/bug
